# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1370, 796)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 651, 71))
        self.groupBox.setObjectName("groupBox")
        self.cboxKDJ = QtWidgets.QCheckBox(self.groupBox)
        self.cboxKDJ.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.cboxKDJ.setChecked(True)
        self.cboxKDJ.setObjectName("cboxKDJ")
        self.cboxDMI = QtWidgets.QCheckBox(self.groupBox)
        self.cboxDMI.setGeometry(QtCore.QRect(120, 30, 91, 16))
        self.cboxDMI.setChecked(True)
        self.cboxDMI.setObjectName("cboxDMI")
        self.cboxMACD = QtWidgets.QCheckBox(self.groupBox)
        self.cboxMACD.setGeometry(QtCore.QRect(230, 30, 91, 16))
        self.cboxMACD.setObjectName("cboxMACD")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(710, 270, 621, 451))
        self.textEdit.setObjectName("textEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(690, 250, 661, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 651, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cboxA300 = QtWidgets.QCheckBox(self.groupBox_3)
        self.cboxA300.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.cboxA300.setChecked(True)
        self.cboxA300.setObjectName("cboxA300")
        self.cboxATotal = QtWidgets.QCheckBox(self.groupBox_3)
        self.cboxATotal.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.cboxATotal.setObjectName("cboxATotal")
        self.cboxA50 = QtWidgets.QCheckBox(self.groupBox_3)
        self.cboxA50.setGeometry(QtCore.QRect(230, 30, 81, 16))
        self.cboxA50.setObjectName("cboxA50")
        self.cboxHKMain = QtWidgets.QCheckBox(self.groupBox_3)
        self.cboxHKMain.setGeometry(QtCore.QRect(330, 30, 81, 16))
        self.cboxHKMain.setObjectName("cboxHKMain")
        self.cboxHKLittle = QtWidgets.QCheckBox(self.groupBox_3)
        self.cboxHKLittle.setGeometry(QtCore.QRect(420, 30, 81, 16))
        self.cboxHKLittle.setObjectName("cboxHKLittle")
        self.cboxUS = QtWidgets.QCheckBox(self.groupBox_3)
        self.cboxUS.setGeometry(QtCore.QRect(530, 30, 81, 16))
        self.cboxUS.setObjectName("cboxUS")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 210, 581, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 270, 621, 451))
        self.tableView.setObjectName("tableView")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 250, 651, 481))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 220, 61, 16))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.btnGo = QtWidgets.QPushButton(self.centralwidget)
        self.btnGo.setGeometry(QtCore.QRect(680, 130, 75, 61))
        self.btnGo.setObjectName("btnGo")
        self.btnLoadStockList = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadStockList.setGeometry(QtCore.QRect(680, 50, 75, 31))
        self.btnLoadStockList.setObjectName("btnLoadStockList")
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()
        self.groupBox.raise_()
        self.textEdit.raise_()
        self.groupBox_3.raise_()
        self.progressBar.raise_()
        self.tableView.raise_()
        self.label.raise_()
        self.btnGo.raise_()
        self.btnLoadStockList.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1370, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        self.btnGo.clicked.connect(MainWindow.OnBtnGoClicked)
        self.btnLoadStockList.clicked.connect(MainWindow.OnBtnOpenStockList)
        MainWindow.destroyed.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cboxA300, self.cboxATotal)
        MainWindow.setTabOrder(self.cboxATotal, self.cboxA50)
        MainWindow.setTabOrder(self.cboxA50, self.cboxHKMain)
        MainWindow.setTabOrder(self.cboxHKMain, self.cboxHKLittle)
        MainWindow.setTabOrder(self.cboxHKLittle, self.cboxUS)
        MainWindow.setTabOrder(self.cboxUS, self.cboxKDJ)
        MainWindow.setTabOrder(self.cboxKDJ, self.cboxDMI)
        MainWindow.setTabOrder(self.cboxDMI, self.cboxMACD)
        MainWindow.setTabOrder(self.cboxMACD, self.btnGo)
        MainWindow.setTabOrder(self.btnGo, self.btnLoadStockList)
        MainWindow.setTabOrder(self.btnLoadStockList, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.tableView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文迪量化客户端"))
        self.groupBox.setTitle(_translate("MainWindow", "策略选择"))
        self.cboxKDJ.setText(_translate("MainWindow", "KDJ金叉预测"))
        self.cboxDMI.setText(_translate("MainWindow", "DMI2买入提示"))
        self.cboxMACD.setText(_translate("MainWindow", "MACD交叉预测"))
        self.groupBox_2.setTitle(_translate("MainWindow", "执行日志"))
        self.groupBox_3.setTitle(_translate("MainWindow", "市场选择"))
        self.cboxA300.setText(_translate("MainWindow", "沪深300"))
        self.cboxATotal.setText(_translate("MainWindow", "沪深全市"))
        self.cboxA50.setText(_translate("MainWindow", "沪深50指数"))
        self.cboxHKMain.setText(_translate("MainWindow", "恒生主板"))
        self.cboxHKLittle.setText(_translate("MainWindow", "恒生中小板"))
        self.cboxUS.setText(_translate("MainWindow", "美股三大指"))
        self.groupBox_4.setTitle(_translate("MainWindow", "选股结果"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">当前进度</span></p></body></html>"))
        self.btnGo.setText(_translate("MainWindow", "Go"))
        self.btnLoadStockList.setText(_translate("MainWindow", "加载列表"))
        self.menu.setTitle(_translate("MainWindow", "数据"))
        self.menu_2.setTitle(_translate("MainWindow", "策略选择"))
        self.menu_3.setTitle(_translate("MainWindow", "收益回测"))
        self.menu_4.setTitle(_translate("MainWindow", "设置"))
        self.menu_5.setTitle(_translate("MainWindow", "关于"))

